### PR TITLE
Use more secure password hashes

### PR DESCRIPTION
**Pull request by fbartels**
Relates to:
- https://github.com/osixia/docker-openldap/issues/48#issuecomment-475393487
- https://github.com/osixia/docker-openldap/issues/351

Fixes https://github.com/osixia/docker-openldap/issues/303

Signed-off-by: Felix Bartels <felix@host-consultants.de>

### CODE REVIEW

**Comment by BertrandGouny** [comment]
Thanks for the PR.

Not sure if we are facing this issue : 

For a new database the admin password is set within the package configuration : 
https://github.com/osixia/docker-openldap/blob/7fb6cc28b5334ece39f44bacf81e3d8fb7a785d2/image/service/slapd/startup.sh#L142 

Then the boostrap ldif are played.

So i guess the admin password remains in SSHA when the container is run for the first time ?

**Comment by kopax** [comment]
Hello, I have just opened #418 

I am not sure what is CRYPT by default, but to me any encryption would be RGPD requirement for production use, we just need NOT to store in clear, do you know if those change would still work?

I am afraid `spring-security-ldap` will only work with Sha password.

**Comment by Keridos** [comment]
@fbartels Does that encrypt already stored passwords?

**Comment by fbartels** [comment]
@Keridos no, this should only affect newly set passwords

**Comment by Keridos** [comment]
@BertrandGouny I think fbartels answered both our questions. You probably need to set the LDAP ADMIN password after the boostrap process.

**Pull request closed without merging**
