### PR TITLE
Fix chmod to make it work on MacOS as well.

### LINKED ISSUE #43: Dockerfile ?
Hi,

I would like to use your image but I like to inspect what I'm about to use in production.

Where to find it ?

Regards,

Cyril

### PR DESCRIPTION
**Pull request by xueshanf**
This should fix #43.

### CODE REVIEW

**Comment by osixia** [comment]
Thanks !
merged in 1.1.9.

I'm also reviewing the pull request #91 that remove the need to chmod.

**Comment by osixia** [comment]
Just pushed the **osixia/openldap:1.1.9-dev** image on docker hub

can you try this one and tell me if it's ok on MacOS ?

**Comment by xueshanf** [comment]
I pulled osixia/openldap:1.1.9-dev and ran a test. Looks good to me:
```
docker run --hostname ldap.example.com --volume $PWD/container/service/slapd/assets/certs:/container/service/slapd/assets/certs \
--env LDAP_TLS_CRT_FILENAME=ldap.crt \
--env LDAP_TLS_KEY_FILENAME=ldap.key \
--env LDAP_TLS_CA_CRT_FILENAME=ca.crt \
--detach osixia/openldap:1.1.9-dev
```
And it responded with a successful search:
```
*** Running /container/run/process/slapd/run...
59247a47 @(#) $OpenLDAP: slapd  (Jan 16 2016 23:00:08) $
	root@chimera:/tmp/buildd/openldap-2.4.40+dfsg/debian/build/servers/slapd
TLS: warning: ignoring dhfile
59247a47 slapd starting
59247ad0 conn=1000 fd=16 ACCEPT from IP=127.0.0.1:54824 (IP=0.0.0.0:389)
59247ad0 conn=1000 op=0 BIND dn="cn=admin,dc=example,dc=org" method=128
59247ad0 conn=1000 op=0 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
59247ad0 conn=1000 op=0 RESULT tag=97 err=0 text=
59247ad0 conn=1000 op=1 SRCH base="dc=example,dc=org" scope=2 deref=0 filter="(objectClass=*)"
59247ad0 conn=1000 op=1 SEARCH RESULT tag=101 err=0 nentries=2 text=
59247ad0 conn=1000 op=2 UNBIND
59247ad0 conn=1000 fd=16 closed
```

**Comment by xueshanf** [comment]
@osixia forgot to mention, the `make build` and `make test` also works on MacOS.

**Comment by osixia** [comment]
Great thanks :)

**Pull request merged**
