### PR TITLE
Replace mail.schema for postfix-book.schema

### PR DESCRIPTION
**Pull request by vivacarvajalito**
I propose to change mail.schema for postfix-book.schema, the reason is not having to create new build just to delete mail and add postfix-book, the replacement does not break any configuration. For compability with docker-mailserver and anothers mail servers. Thanks.

### CODE REVIEW

**Comment by ho-ho-ho** [comment]
Have you already tested this? I also tried sneaking in the exact same `postfix-book.schema` file only to be greeted by an error on startup:
```
Start OpenLDAP...
Waiting for OpenLDAP to start...
Add bootstrap schemas...
5f3cfe79 /container/service/slapd/assets/config/bootstrap/schema/postfix-book.schema: line 21 attributetype: Inconsistent duplicate attributeType: "mailAlias"
slaptest: bad configuration directory!
slaptest conversion failed
Add image bootstrap ldif...
*** /container/run/startup/slapd failed with status 65
```
The problem is `ppolicy.schema` which also defines a `mailAlias` attribute and is loaded automatically even if you don't use it (I don't store plaintext passwords anyway, so it's kinda annoying having to remove that first).

**Comment by ho-ho-ho** [comment]
When I try to use that schema (with an otherwise empty extended docker image), I get this on the first start:
```
Start OpenLDAP...
Waiting for OpenLDAP to start...
Add bootstrap schemas...
5f3d21e2 /container/service/slapd/assets/config/bootstrap/schema/postfix-book.schema: line 21 attributetype: Inconsistent duplicate attributeType: "mailAlias"
slaptest: bad configuration directory!
slaptest conversion failed
Add image bootstrap ldif...
*** /container/run/startup/slapd failed with status 65
```
At first I thought there's some interference with a pre-installed schema file, but that turned out to not be true. Anyone got any clues?

**Comment by vivacarvajalito** [comment]
Hello, thanks for view this, first you have to delete the mail schema, only
that way it works.

**Comment by ho-ho-ho** [comment]
Hello, thanks for the reply.
Just found that out and felt a little stupid :D That's why I deleted the
original message ... but well maybe it helps someone else.
Yeah the amount of preinstalled schemas really gave me a hard time.
Maybe there should be more config options to enable/disable them?

**Comment by vivacarvajalito** [comment]
Thanks for you. Great work.

**Comment by BertrandGouny** [comment]
Thanks :)

**Pull request merged**
