### PR TITLE
Added seeding from internal path.

### PR DESCRIPTION
**Pull request by dbck**
Hi, I have added the possibility to seed ldif or schema from an internal path in the container at startup. See README for more details why I needed it. Hope this is useful for other, too.

### CODE REVIEW

**Comment by BertrandGouny** [comment]
merged in v1.4.0. 
Thanks !

**Comment by dbck** [comment]
@BertrandGouny sorry that I accidentally reopened this merge request. I should have possibly used a dedicated branch.

I added the ability to copy certificates from an internal path.

**Comment by BertrandGouny** [comment]
Oops will merge it again, next release.  Seems incomplete in the stable branch :s

**Comment by BertrandGouny** [comment]
Thanks :)

**Pull request merged**
